extends:
  - airbnb-base
  - prettier

plugins:
  - prettier

rules:
  no-console: ["error", { allow: ["info", "error", "warn"] }]

  prettier/prettier: ["error"]

overrides:
  - files:
      - "*.test.js"

    env:
      jest: true
